PresentationLayer/CookBook.MvcApp/Controllers/DishController.cs
using System;
using System.Web.Mvc;
using System.Web.UI;
using CookBook.Data.MasterData;
using CookBook.Data.UserData;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using CookBook.MvcApp.Models;

namespace CookBook.MvcApp.Controllers
{
    public class DishController : BaseController
    {
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        public ActionResult DishTemperatureMapping()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        public ActionResult RegionalRecipeMap()
        {
            // return View(GetRequestData());
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        public ActionResult SiteRecipeMap()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        public ActionResult GetDishDataList()
        {
            var dishList = ServiceClient.GetDishDataList(null, null, GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        [CustAuthFilter]
        public ActionResult GetRegionDishDataList(int RegionID, string SubSectorCode)
        {
            var dishList = ServiceClient.GetRegionDishDataList(RegionID, null, null, SubSectorCode, GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        [CustAuthFilter]
        public ActionResult GetSiteDishDataList(string siteCode)
        {
            var dishList = ServiceClient.GetSiteDishDataList(siteCode, null, null, GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }

        [CustAuthFilter]
        public ActionResult GetCuisineDataList()
        {
            var dishList = ServiceClient.GetCuisineDataList(GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }

        [CustAuthFilter]
        public ActionResult GetDishRecipeMappingDataList(string DishCode)
        {
            var dishRecipeMappingList = ServiceClient.GetDishRecipeMappingDataList(DishCode, GetRequestData());
            var jsonResult = Json(dishRecipeMappingList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetRegionDishRecipeMappingDataList(int RegionID, string DishCode, string SubSectorCode)
        {
            var regionDishRecipeMappingList = ServiceClient.GetRegionDishRecipeMappingDataList(RegionID, DishCode, SubSectorCode, GetRequestData());
            var jsonResult = Json(regionDishRecipeMappingList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetSiteDishRecipeMappingDataList(string SiteCode, string DishCode)
        {


            var siteDishRecipeMappingList = ServiceClient.GetSiteDishRecipeMappingDataList(SiteCode, DishCode, GetRequestData());
            var jsonResult = Json(siteDishRecipeMappingList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        [ValidateXSS]
        public ActionResult SaveDishData(DishData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0 || model.ID == null)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
                model.Status = (int)StatusEnum.Pending;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }

            var result = ServiceClient.SaveDishData(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [CustAuthFilter]
        public ActionResult SaveDishRecipeMappingList(DishRecipeMappingData[] model)
        {

            var result = ServiceClient.SaveDishRecipeMappingList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustAuthFilter]
        public ActionResult SaveRegionDishRecipeMappingList(RegionDishRecipeMappingData[] model)
        {


            var result = ServiceClient.SaveRegionDishRecipeMappingList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustAuthFilter]
        public ActionResult SaveSiteDishRecipeMappingList(SiteDishRecipeMappingData[] model)
        {


            var result = ServiceClient.SaveSiteDishRecipeMappingList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustAuthFilter]
        public ActionResult SaveDishDataList(DishData[] model)
        {
            var result = ServiceClient.SaveDishDataList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult GetDishCategorySiblingDataList()
        {
            var dishList = ServiceClient.GetDishCategorySiblingDataList(GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        [CustAuthFilter]
        public ActionResult GetRecipeDishDataByDish(string dishCode)
        {
            var recipeList = ServiceClient.GetRecipeDishDataByDish(dishCode, GetRequestData());
            var result = Json(recipeList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        //Krish 28-07-2022
        [CustAuthFilter]
        public ActionResult GetSectorDishDataList(string dishCode = null, string condition = null, bool isAddEdit = false, bool onLoad = false)
        {
            var requestData = GetRequestData();
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            requestData.DishCode = dishCode;
            requestData.SessionUserRoleId = userData.UserRoleId;
            //requestData.RegionID = regionID;
            //requestData.ItemCode = itemCode;

            var dataList = ServiceClient.GetSectorDishData(requestData, condition, isAddEdit, onLoad);
            var jsonResult = Json(dataList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult SaveRangeTypeDishData(string dishCode, string rangeTypeCode)
        {
            var result = ServiceClient.SaveRangeTypeDishData(dishCode, rangeTypeCode, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

PresentationLayer/CookBook.MvcApp/Controllers/ItemController.cs
using ClosedXML.Excel;
using CookBook.Aspects.Factory;
using CookBook.Data;
using CookBook.Data.Request;
using CookBook.Data.UserData;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.DirectoryServices;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using CookBook.Data.MasterData;
using Newtonsoft.Json.Linq;
using Google.Apis.Upload;
using Microsoft.AspNet.Identity;
using CookBook.Aspects.Utils;
using System.Web.UI;
using System.Threading.Tasks;
using System.Reflection;
using System.Web.UI.WebControls;

namespace CookBook.MvcApp.Controllers
{
    public class ItemController : BaseController
    {
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();
        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult UnitPrice()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult ServiceTypeClosingTime()
        {
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult SectorMenu()
        {
            return View(GetRequestData());
        }
        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult SiteMenu()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult RegionMenu()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        public ActionResult GetDishDataList(string SiteCode)
        {
            var requestData = GetRequestData();
            requestData.SiteCode = SiteCode;
            var dishList = ServiceClient.GetDishDataList(null, null, requestData);
            var jsonResult = Json(dishList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetSiteDishDataList(string siteCode)
        {
            var dishList = ServiceClient.GetSiteDishDataList(siteCode, null, null,GetRequestData());
            var jsonResult = Json(dishList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetUnitPriceDataList(string siteCode)
        {
            var dishList = ServiceClient.GetSiteUnitPrice(siteCode, GetRequestData());
            var jsonResult = Json(dishList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetSiteDayPartClossingMappingDataList(string siteCode)
        {
            var dishList = ServiceClient.GetSiteDayPartMapping(siteCode, GetRequestData());
            var jsonResult = Json(dishList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetSiteItemPriceHistory(string siteCode,string itemCode)
        {
            var dishList = ServiceClient.GetSiteItemPriceHistory(siteCode,itemCode, GetRequestData());
            var jsonResult = Json(dishList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetRegionDishMasterData(int regionID)
        {
            var dishList = ServiceClient.GetRegionDishMasterData(regionID, null, null,GetRequestData());
            var jsonResult = Json(dishList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetItemDataList(string SiteCode)
        {
            var requestData = GetRequestData();
            requestData.SiteCode = SiteCode;
            var itemList = ServiceClient.GetItemDataList("", null, null, ((UserMasterResponseData)Session["UserLoginDetails"]).SectorName,requestData);
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetDishImpactedItemList(string dishCode)
        {
            var itemList = ServiceClient.GetDishImpactedItemList(dishCode,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetItemDishMappingDataList(string itemID)
        {
            var itemList = ServiceClient.GetItemDishMappingDataList(itemID,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetItemDishCategoryMappingDataList(string itemCode)
        {
            var itemList = ServiceClient.GetItemDishCategoryMappingDataList(itemCode,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetRegionDishCategoryMappingDataList(string regionID,string itemCode)
        {
           
            var itemList = ServiceClient.GetRegionDishCategoryMappingDataList(regionID, itemCode,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetSiteDishCategoryMappingDataList(string siteCode, string itemCode)
        {
            var itemList = ServiceClient.GetSiteDishCategoryMappingDataList(siteCode, itemCode,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetRegionItemDishMappingDataList(string itemID, string regionID, string subSectorCode)
        {
            RequestData requestData = GetRequestData();
            requestData.SubSectorCode = subSectorCode;
            var itemList = ServiceClient.GetRegionItemDishMappingDataList(itemID, regionID, requestData);
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetSiteItemDayPartMappingDataList(string itemCode, string siteCode)
        {
            var itemList = ServiceClient.GetSiteItemDayPartMappingDataList(itemCode, siteCode, GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetSiteDayPartMappingDataList( string siteCode)
        {
            var itemList = ServiceClient.GetSiteDayPartMappingDataList( siteCode, GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetFoodProgramDayPartMappingDataList(string foodCode)
        {
            var itemList = ServiceClient.GetFoodProgramDayPartMappingDataList(foodCode, GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetSiteItemDishMappingDataList(string itemCode, string siteCode)
        {
            var itemList = ServiceClient.GetSiteItemDishMappingDataList(itemCode, siteCode,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetMasterRegionItemDishMappingDataList(string regionID)
        {
            var itemList = ServiceClient.GetMasterRegionItemDishMappingDataList(regionID,GetRequestData());
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetRegionItemInheritanceMappingDataList(string regionID, string SiteCode)
        {
            var requestData = GetRequestData();
            requestData.SiteCode = SiteCode;
            var itemList = ServiceClient.GetRegionItemInheritanceMappingDataList(regionID, requestData);
            var jsonResult = Json(itemList, JsonRequestBehavior.AllowGet);

PresentationLayer/CookBook.MvcApp/Views/FoodProgram/DishCategory.cshtml
@using CookBook.Data.UserData
@{ 
    UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
}

<script>

    var CookBookMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "CookBookMaster")",
        GetFoodProgramDataList: "@Url.Action("GetFoodProgramDataList", "CookBookMaster")",
        GetDishCategoryDataList: "@Url.Action("GetDishCategoryDataList", "CookBookMaster")",
        GetDishCategorySiblingDataList: "@Url.Action("GetDishCategorySiblingDataList", "Dish")",
        SaveApplicationSettingData: "@Url.Action("SaveApplicationSettingData", "Setting")",
        SaveCafeDataList: "@Url.Action("SaveCafeDataList", "Setting")",
        ChangeStatus: "@Url.Action("SaveFoodProgram", "CookBookMaster")",
        SaveFoodProgram: "@Url.Action("SaveFoodProgram", "CookBookMaster")",
        GetConceptType2DataList: "@Url.Action("GetConceptType2DataList", "CookBookMaster")",
        SaveDishCategory: "@Url.Action("SaveDishCategory", "CookBookMaster")",
        GetDayPartDataList: "@Url.Action("GetDayPartDataList", "CookBookMaster")",
        GetSubSectorMasterList: "@Url.Action("GetSubSectorMasterList", "Item")",
    }
</script>

<script src="~/Scripts/CookBook/DishCategory.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />
<style>

    #DishwindowEdit{
        overflow-y:scroll !important;
    }

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }
    .k-grid-filter.k-state-active {
        background-color: #ddd !important;
    }
</style>
@{
    ViewBag.Title = "Dish Category";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="SiteMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="margin-left: -17px;"></h3>
                        <div class="card-tools" style="margin-top: -6px;">
                            <span style="float:left; margin-top:2px!important">
                                <input type="text" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="    position: relative; right: -277px;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                            </span>
                            <button id="dcaddnew" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="margin-top:5px">
                                Add New
                            </button>
                        </div>
                    </div>
                    <div id="dcid" style="display:none;"></div>
                    <!-- /.card-header -->
                    <div id="dcbody" class="card-body">


                        <div id="gridDishCategory"></div>

                        @if (userData.SectorNumber == "80")
                        {
                            <div id="DishwindowEdit" style="display:none;">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-2 allsector">
                                            <label class="form-control-label">Code</label>
                                            <input type="text" id="dccode" class="form-control" disabled />

                                        </div>
                                        <div class="col-9">

                                            <label class="form-control-label"> Name<span class="mandatoryAsterisk">*</span></label>
                                            <input style="width:95% !important;" type="text" id="dcname" class="form-control" />

                                        </div>
                                    </div>

                                    <div class="row" style="display:none;">
                                        <div class="col-2">
                                            <label class="form-control-label">Sibling Code</label>
                                            <input type="text" id="sbcode" class="form-control" disabled />

                                        </div>
                                        <div class="col-6">

                                            <label class="form-control-label">Mealtime</label>
                                            <div id="inputdaypart" class="form-control"></div>

                                        </div>



                                    </div>


                                    <div class="row" style="margin-top:15px!important">
                                        <div class="col-11">
                                            <div style="width:100%;">  <div class="form-control-label" style="margin-bottom:0px!important;"> Start typing/Select DishCategory Subling to be mapped with Dish Category</div></div>
                                            <div id="inputdishcategoryclear" style="width: 100%;">
                                                <div style="text-align: left;" id="inputdishcategory"></div>

                                            </div>
                                        </div>
                                    </div>



                                    <div class="row">
                                        <div class="col-11">

                                            <button type="submit" id="dcsubmit" class="btn btn-info btn-new-save">Save</button>

                                            <button type="submit" id="dccancel" class="btn btn-tool btn-new-cancel">Cancel</button>
                                        </div>


                                    </div>

                                </div>
                                </div>
                        }
                        else
                        {
                            <div id="DishwindowEdit" style="display:none;">
                                <div class="container">
                                    <div class="first-input">
                                        <div>
                                            <label class="form-control-label">Code</label>
                                            <input type="text" id="dccode" class="form-control" disabled />
                                        </div>


                                    </div>
                                    <div class="first-input">
                                        <div>
                                            <label class="form-control-label"> Name<span class="mandatoryAsterisk">*</span></label>
                                            <input type="text" id="dcname" class="form-control" />
                                        </div>
                                    </div>
                                    @if (userData.SectorNumber == "10")
                                    {
                                        <div class="first-input" >
                                            <div>
                                                <label class="form-control-label">Sub Sector Type<span class="mandatoryAsterisk">*</span></label>
                                                <div id="inputsubsector" class="form-control"></div>
                                            </div>
                                        </div>
                                    }
                                    <div class="first-input">
                                        <div>

                                            <button type="submit" id="dcsubmit" class="btn btn-info btn-new-save">Save</button>

                                            <button type="submit" id="dccancel" class="btn btn-tool btn-new-cancel">Cancel</button>
                                        </div>


                                    </div>

                                </div>
                            </div>
                        }

                    </div>
                    <!-- /.card-body -->
                  
                    <!-- /.card-footer-->
                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<div id="videoPlayingDiv" style="display:none;">
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 5px;">
            <video id="videoclip" width="990" height="550" controls="controls" style="border:1px solid lightgrey;" disablePictureInPicture controlsList="nodownload noplaybackrate" oncontextmenu="return false;">
                <source id="mp4video" src="#" type="video/mp4" />
            </video>
        </div>
    </div>
</div>

PresentationLayer/CookBook.MvcApp/Views/FoodProgram/Reason.cshtml
<script>

    var CookBookMasters = {
          GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "CookBookMaster")",
          SaveReason: "@Url.Action("SaveReason", "CookBookMaster")",

         GetReasonDataList: "@Url.Action("GetReasonList", "Item")",
             GetReasonTypeDataList: "@Url.Action("GetReasonTypeDataList", "CookBookMaster")",

    }
</script>

<script src="~/Scripts/CookBook/Reason.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />
<style>

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }
</style>
@{
    ViewBag.Title = "Reason Master";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="SiteMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">
                        <h3 id="ct" class="card-title" style="margin-left: -17px;"></h3>
                        <div class="card-tools" style="margin-top: -6px;">
                            <span style="float:left; margin-top:2px!important">
                                <input type="text" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="    position: relative; right: -277px;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                            </span>
                            <button id="dpaddnew" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="margin-top:5px">
                                Add New
                            </button>
                        </div>
                    </div>
                    <div id="dpid" style="display:none;"></div>
                    <!-- /.card-header -->
                    <div id="dpbody" class="card-body">


                        <div id="gridReason"></div>
                        <div id="ReaswindowEdit" style="display:none;">
                            <div class="container">
                                <div class="first-input">
                                    <div>
                                        <label class="form-control-label">Code</label>
                                        <input type="text" id="dpcode" class="form-control" disabled />
                                    </div>


                                </div>
                                <div class="first-input">
                                    <div>
                                        <label class="form-control-label"> Description<span class="mandatoryAsterisk">*</span></label>
                                        <input type="text" id="dpname" class="form-control" />
                                    </div>
                                </div>
                                <div id="hiderow" class="first-input">
                                    <div>
                                        <label class="form-control-label"> Reason Type<span class="mandatoryAsterisk">*</span></label>
                                        <input type="text" id="dpreasontype" class="form-control" />
                                    </div>
                                </div>
                                <div class="first-input">
                                    <div style="margin-bottom:45px;">

                                        <button type="submit" id="secredpsubmit" class="btn btn-info btn-new-save">Save</button>

                                        <button type="submit" id="secredpcancel" class="btn btn-tool btn-new-cancel">Cancel</button>
                                    </div>


                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<div id="videoPlayingDiv" style="display:none;">
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 5px;">
            <video id="videoclip" width="990" height="550" controls="controls" style="border:1px solid lightgrey;" disablePictureInPicture controlsList="nodownload noplaybackrate" oncontextmenu="return false;">
                <source id="mp4video" src="#" type="video/mp4" />
            </video>
        </div>
    </div>
</div>