PresentationLayer/CookBook.MvcApp/Controllers/LevelMasterController.cs
using CookBook.Data.MasterData;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CookBook.MvcApp.Controllers
{
    public class LevelMasterController : BaseController
    {
        // GET: LevelMaster
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();
        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        public ActionResult GetLevelMasterList()
        {
            var mogList = ServiceClient.GetLevelDataList(GetRequestData());
            return Json(mogList, JsonRequestBehavior.AllowGet);
        }


        [CustAuthFilter]
        public ActionResult SaveManageLevelInfo(LevelMasterData model)
        {
            string UserName = string.Empty;
            var UserInstance = HttpContext.User.Identity as System.Security.Claims.ClaimsIdentity;
            if (UserInstance.IsAuthenticated)
            {
                UserName = UserInstance.FindFirst("preferred_username").Value;
            }
            var res = ServiceClient.GetUserData(UserName, null);
            int username = res.UserId;
            var regionRecipeList = ServiceClient.SaveManageLevelInfo(GetRequestData(), model, username);
            var jsonResult = Json(regionRecipeList, JsonRequestBehavior.AllowGet);

            return Json(jsonResult, JsonRequestBehavior.AllowGet);

        }
        [CustAuthFilter]
        public ActionResult UpdateManageLevelInfo(LevelMasterData model)
        {
            string UserName = string.Empty;
            var UserInstance = HttpContext.User.Identity as System.Security.Claims.ClaimsIdentity;
            if (UserInstance.IsAuthenticated)
            {
                UserName = UserInstance.FindFirst("preferred_username").Value;
            }
            var res = ServiceClient.GetUserData(UserName, null);
            int username = res.UserId;
            var regionRecipeList = ServiceClient.UpdateManageLevelInfo(GetRequestData(), model, username);
            var jsonResult = Json(regionRecipeList, JsonRequestBehavior.AllowGet);

            return Json(jsonResult, JsonRequestBehavior.AllowGet);

        }

        [CustAuthFilter]
        public ActionResult UpdateLevelInactiveActive(LevelMasterData model)
        {
            string UserName = string.Empty;
            var UserInstance = HttpContext.User.Identity as System.Security.Claims.ClaimsIdentity;
            if (UserInstance.IsAuthenticated)
            {
                UserName = UserInstance.FindFirst("preferred_username").Value;
            }
            var res = ServiceClient.GetUserData(UserName, null);
            int username = res.UserId;
            var regionRecipeList = ServiceClient.UpdateLevelInactiveActive(GetRequestData(), model, username);
            var jsonResult = Json(regionRecipeList, JsonRequestBehavior.AllowGet);

            return Json(jsonResult, JsonRequestBehavior.AllowGet);

        }
    }
}

PresentationLayer/CookBook.MvcApp/Views/LevelMaster/Index.cshtml
<script>

    var CookBookMasters = {
        GetLevelMasterList: "@Url.Action("GetLevelMasterList", "LevelMaster")",
        SaveManageLevelInfo: "@Url.Action("SaveManageLevelInfo", "LevelMaster")",
        UpdateManageLevelInfo: "@Url.Action("UpdateManageLevelInfo", "LevelMaster")",
        UpdateLevelInactiveActive: "@Url.Action("UpdateLevelInactiveActive", "LevelMaster")",
    }
</script>

<script src="~/Scripts/CookBook/LevelMaster.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />
<style>
    #GETALLMogViewALLHistoryBATCHWISE .k-grid-content {
        min-height: 100px;
        max-height: 200px;
    }

    #inputSectorClear .k-input[readonly] {
        background-color: #e2e2e2 !important;
        color: #2e2e2e;
    }

    .m-link {
        cursor: pointer !important;
        color: #a09b9b;
        font-size: 0.8em;
        margin-right: 4px;
    }

    .k-grid-MapAPL {
        color: #76b4b0 !important;
    }

    .statuscolu {
        color: orangered !important;
    }

    #windowEditMOGWiseAPL .card-header {
        padding-top: 0px !important;
    }

    #windowEditMOGWiseAPL .container {
        padding-left: 5px !important;
    }

    #changesum:hover {
        background: none !important;
    }

    .btn-tool:hover {
        background-color: transparent !important;
    }

    .checkbox-container .checkmark:after {
        left: 3.5px !important;
        top: 1px !important;
    }

    .info-box {
        min-height: 45px !important;
        padding: 0px !important;
        border: 1px solid #00000047;
    }

    .info-box-padding {
        /* padding-left: 0px !important;
        padding-right: 0px !important;*/
        margin-right: 23px !important;
    }

    /*#finalRecipeGrid, #baseRecipeGrid, #dishGrid, #itemGrid, #siteGrid .k-grid-content.k-auto-scrollable {
        height: 150px !important;
        max-height: 150px !important;
    }*/

    #windowEditMOGDependencies .k-grid-content.k-auto-scrollable {
        height: 150px !important;
        max-height: 150px !important;
    }

    .batchstatuscolor {
        color: forestgreen !important;
    }

    .batchstatuscolorred {
        color: orangered !important;
    }

    .ViewBatch {
        color: #b7aeae !important;
    }

    #windowEditMOGDependencies .k-grid {
        width: 99% !important;
    }


    h6 {
        font-weight: 600 !important;
        margin-top: 10px !important;
    }

    .dependencies-scroll {
        max-height: 360px;
        overflow-y: scroll !important;
        overflow-x: hidden;
    }

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }

    #windowEditMOGDependencies .k-grid-norecords-template {
        background-color: #fff;
        border: none !important;
        font-size: 20px !important;
    }

    .colortag {
        height: 13px;
        width: 12px;
        border-radius: 9px;
        margin-left: 22px;
        background-color: blue;
    }
</style>
@{
    ViewBag.Title = "Manage Level Master";
}
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <input id="isRIEnabled" type="hidden" value="@System.Configuration.ConfigurationManager.AppSettings["isRIEnabled"]" />
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">



                <div id="MOGMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="margin-left: -12px;margin-top: 7px;"></h3>

                        <div class="card-tools" style="margin-top: -6px;">

                            @*<a href="MOG/DownloadExcTemplate/" target="_blank" class="btn btn-tool" style="margin-top:20px;"> Export To Template</a>*@
                            <button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="padding-top:7px">
                                Export To Excel
                            </button>

                            <span style="float:left">
                                <input type="text" style=" margin-top: 8px;" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="position: relative; right: -277px;top: 7px;font-size: 0.8em;color: #76b4b0;"></i>
                            </span>


                            <button id="LevelAddNew" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="margin-top:5px; ">
                                Add New
                            </button>


                        </div>
                    </div>

                    <div id="fpbody" class="card-body">


                        <div id="gridLevelList"></div>







                    </div>
                    <!-- /.card-body -->
                    <!-- /.card-footer-->
                </div>

                <input type="hidden" id="sectorid" />

                <div id="LevelwindowEdit" style="display:none;">
                    <div class="container">
                        <div class="row">
                            <div class="col-4" id="LevelCodeDiv" style="min-width:85px!important">
                                <label class="form-control-label" style="margin-left: -7px;">Level Name<span class="mandatoryAsterisk">*</span></label>
                                <input type="text" id="txt_Levelname" class="form-control" style="margin-left: -8px;" />
                            </div>

                            <div class="col-7" id="LevelDiv">
                                <label class="form-control-label">Level Description<span class="mandatoryAsterisk">*</span></label>
                                <input type="text" id="txt_Leveldesc" class="form-control" />
                            </div>

                        </div>

                        <div class="row" style="float:right;">
                            <div class="col-11">
                                <button type="submit" id="Levelcancel" class="btn btn-tool">Cancel</button>
                                <button type="submit" id="LevelSubmit" style="margin-top: 9px !important;" class="btn btn-info">Save</button>
                            </div>


                        </div>

                    </div>
                </div>

                <div id="LevelwindowEdit1" style="display:none;">
                    <div class="container">
                        <div class="row">
                            <div class="col-4" id="LevelCodeDiv" style="min-width:85px!important">
                                <label class="form-control-label" style="margin-left: -7px;">Level Name<span class="mandatoryAsterisk">*</span></label>
                                <input type="text" id="txt_LevelnameEdit" class="form-control" style="margin-left: -8px;" />
                            </div>

                            <div class="col-7" id="LevelDivEdit">
                                <label class="form-control-label">Level Description<span class="mandatoryAsterisk">*</span></label>
                                <input type="text" id="txt_LeveldescEdit" class="form-control" />
                            </div>

                        </div>

                        <div class="row" style="float:right;">
                            <div class="col-11">
                                <button type="submit" id="LevelcancelEdit" class="btn btn-tool">Cancel</button>
                                <button type="submit" id="LevelSubmitEdit" style="margin-top: 9px !important;" class="btn btn-info">Save</button>
                            </div>


                        </div>

                    </div>
                </div>


            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>