PresentationLayer/CookBook.MvcApp/Controllers/DishController.cs
using System;
using System.Web.Mvc;
using System.Web.UI;
using CookBook.Data.MasterData;
using CookBook.Data.UserData;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using CookBook.MvcApp.Models;

namespace CookBook.MvcApp.Controllers
{
    public class DishController : BaseController
    {
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        public ActionResult DishTemperatureMapping()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        public ActionResult RegionalRecipeMap()
        {
            // return View(GetRequestData());
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        public ActionResult SiteRecipeMap()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }
        [CustAuthFilter]
        public ActionResult GetDishDataList()
        {
            var dishList = ServiceClient.GetDishDataList(null, null, GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        [CustAuthFilter]
        public ActionResult GetRegionDishDataList(int RegionID, string SubSectorCode)
        {
            var dishList = ServiceClient.GetRegionDishDataList(RegionID, null, null, SubSectorCode, GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        [CustAuthFilter]
        public ActionResult GetSiteDishDataList(string siteCode)
        {
            var dishList = ServiceClient.GetSiteDishDataList(siteCode, null, null, GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }

        [CustAuthFilter]
        public ActionResult GetCuisineDataList()
        {
            var dishList = ServiceClient.GetCuisineDataList(GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }

        [CustAuthFilter]
        public ActionResult GetDishRecipeMappingDataList(string DishCode)
        {
            var dishRecipeMappingList = ServiceClient.GetDishRecipeMappingDataList(DishCode, GetRequestData());
            var jsonResult = Json(dishRecipeMappingList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetRegionDishRecipeMappingDataList(int RegionID, string DishCode, string SubSectorCode)
        {
            var regionDishRecipeMappingList = ServiceClient.GetRegionDishRecipeMappingDataList(RegionID, DishCode, SubSectorCode, GetRequestData());
            var jsonResult = Json(regionDishRecipeMappingList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        public ActionResult GetSiteDishRecipeMappingDataList(string SiteCode, string DishCode)
        {


            var siteDishRecipeMappingList = ServiceClient.GetSiteDishRecipeMappingDataList(SiteCode, DishCode, GetRequestData());
            var jsonResult = Json(siteDishRecipeMappingList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        [CustAuthFilter]
        [ValidateXSS]
        public ActionResult SaveDishData(DishData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0 || model.ID == null)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
                model.Status = (int)StatusEnum.Pending;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }

            var result = ServiceClient.SaveDishData(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [CustAuthFilter]
        public ActionResult SaveDishRecipeMappingList(DishRecipeMappingData[] model)
        {

            var result = ServiceClient.SaveDishRecipeMappingList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustAuthFilter]
        public ActionResult SaveRegionDishRecipeMappingList(RegionDishRecipeMappingData[] model)
        {


            var result = ServiceClient.SaveRegionDishRecipeMappingList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustAuthFilter]
        public ActionResult SaveSiteDishRecipeMappingList(SiteDishRecipeMappingData[] model)
        {


            var result = ServiceClient.SaveSiteDishRecipeMappingList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [CustAuthFilter]
        public ActionResult SaveDishDataList(DishData[] model)
        {
            var result = ServiceClient.SaveDishDataList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult GetDishCategorySiblingDataList()
        {
            var dishList = ServiceClient.GetDishCategorySiblingDataList(GetRequestData());
            var result = Json(dishList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        [CustAuthFilter]
        public ActionResult GetRecipeDishDataByDish(string dishCode)
        {
            var recipeList = ServiceClient.GetRecipeDishDataByDish(dishCode, GetRequestData());
            var result = Json(recipeList, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
        //Krish 28-07-2022
        [CustAuthFilter]
        public ActionResult GetSectorDishDataList(string dishCode = null, string condition = null, bool isAddEdit = false, bool onLoad = false)
        {
            var requestData = GetRequestData();
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            requestData.DishCode = dishCode;
            requestData.SessionUserRoleId = userData.UserRoleId;
            //requestData.RegionID = regionID;
            //requestData.ItemCode = itemCode;

            var dataList = ServiceClient.GetSectorDishData(requestData, condition, isAddEdit, onLoad);
            var jsonResult = Json(dataList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult SaveRangeTypeDishData(string dishCode, string rangeTypeCode)
        {
            var result = ServiceClient.SaveRangeTypeDishData(dishCode, rangeTypeCode, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

PresentationLayer/CookBook.MvcApp/Controllers/RecipeCopyController.cs
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CookBook.MvcApp.Controllers
{
    public class RecipeCopyController : BaseController
    {
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            return PartialView(GetRequestData());
        }
    }
}

PresentationLayer/CookBook.MvcApp/Controllers/SettingController.cs
using System;
using System.Web.Mvc;
using CookBook.Data.MasterData;
using CookBook.Data.UserData;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;

namespace CookBook.MvcApp.Controllers
{
    public class SettingController : BaseController
    {
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();
      
     
        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            return View(GetRequestData());
        }
      
        [CustAuthFilter]
        public ActionResult GetApplicationSettingDataList()
        {
            var asList = ServiceClient.GetApplicationSettingDataList(GetRequestData());
            var jsonResult = Json(asList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

      
        [CustAuthFilter]
        [ValidateXSS]
        public ActionResult SaveApplicationSettingData(ApplicationSettingData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }
            var result = ServiceClient.SaveApplicationSettingData(model,GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult ChangeStatus(ApplicationSettingData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            model.ModifiedBy = userData.UserId;
            model.ModifiedOn = DateTime.Now;
            var result = ServiceClient.SaveApplicationSettingData(model,GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }


    



    }
}

PresentationLayer/CookBook.MvcApp/Controllers/SiteController.cs
using ClosedXML.Excel;
using CookBook.Aspects.Factory;
using CookBook.Data;
using CookBook.Data.Request;
using CookBook.Data.UserData;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.DirectoryServices;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using CookBook.Data.MasterData;

namespace CookBook.MvcApp.Controllers
{
    public class SiteController : BaseController
    {
        private ICookBookService ServiceClient = ServiceHelper.GetCookBookService();

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            //return View(GetRequestData());
            return PartialView(GetRequestData());
        }

        [CustAuthFilter]
        public ActionResult GetSiteDataList(string SiteCode)
        {
            var requestData = GetRequestData();
            requestData.SiteCode = SiteCode;
            var siteList = ServiceClient.GetSiteMasterDataList(requestData);
            var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        //Krish        
        [CustAuthFilter]
        public ActionResult GetSiteByRegionDataList(int regionId)
        {
            var siteList = ServiceClient.GetSiteByRegionDataList(regionId, GetRequestData());
            var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
        //Krish        
        [CustAuthFilter]
        public ActionResult GetSiteByUserDataList()
        {
            var siteList = ServiceClient.GetSiteDetailsByUserIdDataList(GetRequestData());
            var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetSiteDataListByUserId()
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (userData.IsSectorUser)
            {
                var siteList = ServiceClient.GetSiteMasterDataList(GetRequestData());
                var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = Int32.MaxValue;
                return jsonResult;
            }
            else
            {
                var siteList = ServiceClient.GetSiteDetailsByUserIdDataList(GetRequestData());
                var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = Int32.MaxValue;
                return jsonResult;
            }
        }

        [CustAuthFilter]
        [ValidateXSS]
        public ActionResult SaveSiteData(SiteMasterData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            model.ModifiedBy = userData.UserId.ToString();
            model.ModifiedDate = DateTime.Now;

            var result = ServiceClient.SaveSiteData(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult ChangeStatus(SiteMasterData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];
            model.ModifiedBy = userData.UserId.ToString();
            model.ModifiedDate = DateTime.Now;
            var result = ServiceClient.SaveSiteData(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult SaveSiteDataList(SiteMasterData[] model)
        {
            var result = ServiceClient.SaveSiteDataList(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [CustAuthFilter]
        public ActionResult GetCPUDataList()
        {
            var siteList = ServiceClient.GetCPUDataList(GetRequestData());
            var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }

        [CustAuthFilter]
        public ActionResult GetDKDataList()
        {
            var siteList = ServiceClient.GetDKDataList(GetRequestData());
            var jsonResult = Json(siteList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }
    }
}

PresentationLayer/CookBook.MvcApp/Views/RecipeCopy/Index.cshtml
<script>

    var CookBookMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "CookBookMaster")",
        GetDishDataList: "@Url.Action("GetDishDataList", "Dish")",
        GetMOGDataList: "@Url.Action("GetMOGDataList", "MOG")",
        GetUOMDataList: "@Url.Action("GetUOMDataList", "CookBookMaster")",
        GetRecipeDataList: "@Url.Action("GetRecipeDataList", "Recipe")",
        GetBaseRecipesByRecipeID: "@Url.Action("GetBaseRecipesByRecipeID", "Recipe")",
        GetMOGsByRecipeID: "@Url.Action("GetMOGsByRecipeID", "Recipe")",
        SaveRecipeData: "@Url.Action("SaveRecipeData", "Recipe")",
        SaveRecipeDataList: "@Url.Action("SaveRecipeDataList", "Recipe")",
        GetAPLMasterDataListForMOG: "@Url.Action("GetAPLMasterDataListForMOG", "APLMaster")",
        GetRecipeImpactedDataList: "@Url.Action("GetRecipeImpactedDataList", "Recipe")",
        SendRecipeEmail: "@Url.Action("SendRecipeEmail", "Recipe")",
        GetApplicationSettingDataList: "@Url.Action("GetApplicationSettingDataList", "Setting")",
        GetUOMModuleMappingDataList: "@Url.Action("GetUOMModuleMappingDataList", "CookBookMaster")",
        GetNutritionMasterDataList: "@Url.Action("GetNutritionMasterDataList", "CookBookMaster")",
        SaveRecipeNutrientMappingData: "@Url.Action("SaveRecipeNutrientMappingData", "Recipe")",
        GetMOGUOMDataList: "@Url.Action("GetMOGUOMDataList", "MOG")",
        GetSiteDataListByUserId: "@Url.Action("GetSiteDataListByUserId", "Site")",
        GetSiteRecipeDataList: "@Url.Action("GetSiteRecipeDataList", "Recipe")",
        SaveRecipeCopy:"@Url.Action("SaveRecipeCopy", "Recipe")",

        GetRecipePrintingData:"@Url.Action("GetRecipePrintingData", "Recipe")",
    }
</script>
<style>
    .checkbox-container .checkmarkgrid:after {
        left: 3.4px !important;
    }

    .siteinputdiv .k-dropdown .k-input {
        padding: 6px 0 !important;
        font-size: 12px !important;
    }

    .siteinputdiv span.k-icon.k-i-arrow-s {
        top: 9px !important;
    }
     /*.k-dropdown .k-input {
        height: 30px !important;
        line-height: 1.65em !important;
        padding: 0.097em 0 !important;
        font-size: 12px !important;
    }*/

    .k-multiselect-wrap {
        background-color: #dddddd !important;
    }

    .k-dropdown-wrap.k-state-default {
        background-color: #fff;
        min-height: inherit !important;
        padding: 0em 0;
        font-size: 13px;
        height: 30px !important;
    }

    #inputsitemulti {
        max-height: 100px !important;
    }

    input.k-checkbox {
        display: inline;
        opacity: 0;
        width: 0;
        margin: 0;
        -webkit-appearance: checkbox;
        overflow: hidden;
    }

    .row-checkbox {
        margin-left: 20px;
    }

    .search-input {
        margin-right: 0px !important;
    }

    .k-checkbox-md {
        border: 1px solid #76b4b0;
    }

    

</style>
@*<script src="~/Scripts/CookBook/Recipe.js"></script>*@

<script src="~/Scripts/CookBook/RecipeCopy.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row" style="margin-top:2px!important;">
            <div class="col-12">
                <div id="success" class="alert alert-success alert-dismissible" style="display:none;width:100%;">
                    <i class="icon fas fa-check"></i>
                    <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                    </p>
                </div>
            </div>

            <!-- Left col -->
            <section id="mainContent" class="col-sm-12 " style="display: inherit;min-height: 480px;">
                <div id="RecipeMaster" class="col-lg-12 card direct-chat direct-chat-primary" style="display:block;margin-top:0!important">
                    <div class="card-header" style="padding-top:0px!important;">
                        <div class="row">
                            <div class="col-md-4 siteinputdiv" style="padding-left:0;">
                                <label class="form-control-label" style="margin-left: -13px;">Select Copy from Unit</label>
                                <div style="height:30px !important; display:block;width:100%!important; margin-left:-13px; margin-top:7px!important; margin-right:10px; text-align: left;" id="inputsite" class="form-control">

                                </div>
                            </div>
                            <div class="col-md-7">
                                <label class="form-control-label">Select Copy to Unit</label>
                                <div style="height: 33px !important;background-color: #dddddd; display: block;margin-top: 7px !important;text-align: left;" id="inputsitemulti" class="form-control">

                                </div>
                            </div>
                            <div class="col-md-1" style="text-align: right; ">
                                <button id="btnGo" type="submit" class="btn  btn-info" data-toggle="tooltip" title=""
                                        data-widget="chat-pane-toggle" style=" display: inline-block; height: 32px; margin-left: -3px !important; margin-top: 27px !important; padding-top: 0px !important; padding-bottom: 2px !important; padding-top: 2px !important;">
                                    Apply
                                </button>
                            </div>
                        </div>

                        @*<button id="btnGo" type="submit" class="btn  btn-info" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="display:none;margin-left:-6px!important;margin-top:8px!important">
                                Go
                            </button>*@
                        <span id="searchspan" style="float:right; margin-top:2px!important; display:none">
                            <input type="text" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                            <i class="fas fa-search" style="    position: relative; right: -277px;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                        </span>
                    </div>
                    <!-- /.card-header -->
                    <div class="row">
                        <div class="col-12" style="padding-left:0;">
                            <div id="fpbody" class="card-body" style="overflow: hidden;">
                                <div id="bulkerror" class="alert alert-danger alert-dismissible" style="display:none">
                                    <i class="icon fas fa-exclamation"></i>
                                    <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                                    </p>
                                </div>


                                <div id="gridRecipe"></div>

                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </div>
    </div>
</section>
<div id="videoPlayingDiv" style="display:none;">
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 5px;">
            <video id="videoclip" width="990" height="550" controls="controls" style="border:1px solid lightgrey;" disablePictureInPicture controlsList="nodownload noplaybackrate" oncontextmenu="return false;">
                <source id="mp4video" src="#" type="video/mp4" />
            </video>
        </div>
    </div>
</div>