PresentationLayer/CookBook.MvcApp/Controllers/ColorController.cs
using ClosedXML.Excel;
using CookBook.Aspects.Factory;
using CookBook.Data;
using CookBook.Data.Request;
using CookBook.Data.UserData;
using CookBook.MvcApp.Core;
using CookBook.MvcApp.Filters;
using CookBook.MvcApp.CookBookService;
using CookBook.MvcApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.DirectoryServices;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using CookBook.Data.MasterData;
using CookBook.ServiceApp;
using System.Net;
using Newtonsoft.Json;
using CookBook.Aspects.Utils;
using CookBook.Aspects.Constants;
using Rotativa;
using static CookBook.MvcApp.Filters.CustAuthFilter;

namespace CookBook.MvcApp.Controllers
{
    public class ColorController : BaseController
    {
        private CookBookService.ICookBookService ServiceClient = ServiceHelper.GetCookBookService();

        [CustAuthFilter]
        [LogRequestDetailsAttribute]
        public ActionResult Index()
        {
            return PartialView("Index");
        }

        [CustAuthFilter]
        public ActionResult GetColorDataList()
        {

            var colorList = ServiceClient.GetColorDataList( GetRequestData());
            var jsonResult = Json(colorList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = Int32.MaxValue;
            return jsonResult;
        }


        [CustAuthFilter]
        [ValidateXSS]
        public ActionResult SaveColorData(ColorData model)
        {
            UserMasterResponseData userData = (UserMasterResponseData)Session["UserLoginDetails"];

            if (model.ID == 0)
            {
                model.CreatedBy = userData.UserId;
                model.CreatedOn = DateTime.Now;
            }
            else
            {
                model.ModifiedBy = userData.UserId;
                model.ModifiedOn = DateTime.Now;
            }
            var result = ServiceClient.SaveColorData(model, GetRequestData());
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        [CustAuthFilter]
        public ActionResult GeneratePDF()
        {
            var pdf = new ViewAsPdf("SamplePDF");
            var pdfContent = pdf.BuildFile(ControllerContext);

            // Specify the path where you want to save the PDF
            string filePath = Server.MapPath("~/pdfs/example.pdf");

            // Save the PDF content to the specified path
            System.IO.File.WriteAllBytes(filePath, pdfContent);

            // Return the path to the JavaScript file
            ViewBag.PdfFilePath = filePath;
            return Content(filePath);
        }

        [CustAuthFilter]
        public ActionResult DownloadPDF()
        {
            // Specify the path to the PDF file
            string filePath = Server.MapPath("~/pdfs/example.pdf");

            // Check if the file exists
            if (!System.IO.File.Exists(filePath))
            {
                return HttpNotFound(); // or return a custom error view
            }

            // Return the file as a response
            return File(filePath, "application/pdf", "example.pdf");
        }

    }
}

PresentationLayer/CookBook.MvcApp/Views/Color/Index.cshtml
@*<div class="modal-body" id="partialcolordiv">
        @Html.Partial("_ColorPartial")
    </div>*@

<script>

    var CookBookMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "CookBookMaster")",
        GetColorDataList: "@Url.Action("GetColorDataList", "Color")",
        SaveColorData: "@Url.Action("SaveColorData", "Color")",
        SavePDF: "@Url.Action("GeneratePDF", "Color")",
    }

    
</script>

<!-- bootstrap color picker -->
<script src="~/Content/css/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>

<script src="~/Scripts/CookBook/Color.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />
<!-- Bootstrap Color Picker -->
<link href="~/Content/css/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet" />
<style>
    .popover {
        z-index: 120000 !important;
    }

   /* .k-window {
        height: 230px !important;
    }*/

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }

   /* #videoclip{
        height:500px !important;
    }*/
</style>
@{
    ViewBag.Title = "Manage Colors";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="ColorMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">


                        <div class="card-tools" style="margin-top: -6px;">
                            <span style="float:left; margin-top:2px!important">
                                <input type="text" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="    position: relative; right: -277px;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                            </span>
                            <button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="padding-top:7px">
                                Export To Excel
                            </button>
                            <button id="AddNew" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="margin-top:5px">
                                Add New Color
                            </button>

                        </div>
                    </div>
                    <div id="colorid" style="display:none;"></div>
                    <!-- /.card-header -->
                    <div id="clbody" class="card-body">
                        <div id="bulkerror" class="alert alert-danger alert-dismissible" style="display:none">
                            <i class="icon fas fa-exclamation"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="success" class="alert alert-success alert-dismissible" style="display:none">
                            <i class="icon fas fa-check"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="gridColor"></div>
                        <div id="ColorwindowEdit" style="display:none;">
                            <div class="container">
                                <div id="error" class="alert alert-danger alert-dismissible" style="display:none">
                                    <i class="icon fas fa-exclamation"></i>
                                    <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                                    </p>
                                </div>
                                <div class="row" style="padding-top: 10px!important">
                                    @*<div class="col-2" style="display:none">*@
                                    <label class="form-control-label">Color Code</label>
                                    <input type="text" id="colorcode" class="form-control" disabled />
                                    @*</div>*@
                                    @*<div class="col-12">*@
                                    <div class="input-group my-colorpicker2" style="padding-top: 10px !important;">
                                        <label class="form-control-label">Click to Select Color<span class="mandatoryAsterisk">*</span></label>
                                        <input type="text" id="colorselect" class="form-control" style="width: 80px !important;border-radius: 5px; height: 32px !important;">

                                        <div class="input-group-append">
                                            <span class="input-group-text" style="height: 19px; width: 123px; margin-left: 10px; background-color: rgb(39, 172, 16); border-radius: 5px;"><i class="fas fa-square"></i></span>
                                        </div>
                                        @*</div>*@
                                        @*<div class="input-group my-colorpicker2 colorpicker-element" data-colorpicker-id="2">
                                                <input type="text" id="colorselect" class="form-control" data-original-title="" title="">

                                                <div class="input-group-append">
                                                    <span class="input-group-text"><i class="fas fa-square" style="color: rgb(255, 0, 0);"></i></span>
                                                </div>
                                            </div>*@
                                        @*<label class="form-control-label">Color Selector</label>
                                            <input type="text" id="colorselect" class="form-control" />*@
                                    </div>

                                    <label style="padding-top: 10px!important" class="form-control-label">Color Name<span class="mandatoryAsterisk">*</span></label>
                                    <input type="text" id="colorname" class="form-control" />
                                </div>

                                <div class="row">
                                    <div class="col-2" style="display:none">
                                        <label class="form-control-label">Font Color</label>
                                        <input type="text" id="inputfontcode" class="form-control" />
                                    </div>

                                    <div class="col-4" style="display:none">
                                        <label class="form-control-label">RGB</label>
                                        <input id="inputrgbcode" disabled class="form-control" />
                                    </div>
                                    <div style="display:none">
                                        <label class="form-control-label">Hex Code</label>
                                        <input type="text" disabled id="inputhexcode" class="form-control" />
                                    </div>

                                </div>
                                <div style="margin-top:10px;margin-bottom:10px!important;">
                                    <div class="modal-footer col" style="padding-right:7.5px!important; align-items:flex-end!important">
                                        <button type="submit" id="btnCancel" class="btn btn-tool">Cancel</button>
                                        <button type="submit" id="btnSubmit" class="btn btn-info">Save</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <!-- /.card-footer-->
                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>

<div id="videoPlayingDiv" style="display:none;">
    <div class="row">
        <div class="col-sm-12" style="padding-bottom: 5px;">
            <video id="videoclip" width="990" height="550" controls="controls" style="border:1px solid lightgrey;" disablePictureInPicture controlsList="nodownload noplaybackrate" oncontextmenu="return false;">
                <source id="mp4video" src="#" type="video/mp4" />
            </video>
        </div>
    </div>
</div>

PresentationLayer/CookBook.MvcApp/Views/Color/SamplePDF.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SamplePDF</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

PresentationLayer/CookBook.MvcApp/Views/Color/_ColorPartial.cshtml
@*<div class="modal-body" id="partialcolordiv">
        @Html.Partial("_ColorPartial")
    </div>*@

<script>

    var CookBookMasters = {
        GetLoginUserDetailsUrl: "@Url.Action("GetLoginUserDetails", "CookBookMaster")",
        GetColorDataList: "@Url.Action("GetColorDataList", "Color")",
        SaveColorData: "@Url.Action("SaveColorData", "Color")",
    }
</script>

<!-- bootstrap color picker -->
<script src="~/Content/css/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>

<script src="~/Scripts/CookBook/Color.js"></script>
<link href="~/Content/css/styles.css" rel="stylesheet" />
<!-- Bootstrap Color Picker -->
<link href="~/Content/css/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet" />
<style>
    .popover {
        z-index: 120000 !important;
    }

    .k-window {
        height: 230px !important;
    }

    .slider {
        top: 6px !important;
        bottom: -6px !important;
    }
</style>
@{
    ViewBag.Title = "Manage Colors";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-sm-12 connectedSortable" style="display:inherit; min-height:480px">
                <div id="ColorMaster" class="col-lg-12 card direct-chat direct-chat-primary">
                    <div class="card-header">


                        <div class="card-tools" style="margin-top: -6px;">
                            <span style="float:left; margin-top:2px!important">
                                <input type="text" id="myInput" placeholder="Search" class="search-input" title="Start typing to filter">
                                <i class="fas fa-search" style="    position: relative; right: -277px;top: 4px;font-size: 0.7em;color: #76b4b0;"></i>
                            </span>
                            <button id="btnExport" type="submit" class="btn btn-tool" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="padding-top:7px">
                                Export To Excel
                            </button>
                            <button id="AddNew" type="submit" class="btn btn-success btn-xs" data-toggle="tooltip" title=""
                                    data-widget="chat-pane-toggle" style="margin-top:5px">
                                Add New Color
                            </button>

                        </div>
                    </div>
                    <div id="colorid" style="display:none;"></div>
                    <!-- /.card-header -->
                    <div id="clbody" class="card-body">
                        <div id="bulkerror" class="alert alert-danger alert-dismissible" style="display:none">
                            <i class="icon fas fa-exclamation"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="success" class="alert alert-success alert-dismissible" style="display:none">
                            <i class="icon fas fa-check"></i>
                            <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                            </p>
                        </div>
                        <div id="gridColor"></div>
                        <div id="windowEdit">
                            <div class="container">
                                <div id="error" class="alert alert-danger alert-dismissible" style="display:none">
                                    <i class="icon fas fa-exclamation"></i>
                                    <p style="font-size: 12px;margin-bottom: .15rem;margin-left: 5px;">
                                    </p>
                                </div>
                                <div class="row" style="padding-top: 10px!important">
                                    @*<div class="col-2" style="display:none">*@
                                    <label class="form-control-label">Color Code</label>
                                    <input type="text" id="colorcode" class="form-control" disabled />
                                    @*</div>*@
                                    @*<div class="col-12">*@
                                    <div class="input-group my-colorpicker2" style="padding-top: 10px!important">
                                        <label class="form-control-label">Click to Select Color<span class="mandatoryAsterisk">*</span></label>
                                        <input type="text" id="colorselect" class="form-control" style="width: 80px !important;border-radius: 5px; height: 32px !important;">

                                        <div class="input-group-append">
                                            <span class="input-group-text" style="height: 19px; width: 123px; margin-left: 10px; background-color: rgb(39, 172, 16); border-radius: 5px;"><i class="fas fa-square"></i></span>
                                        </div>
                                        @*</div>*@
                                        @*<div class="input-group my-colorpicker2 colorpicker-element" data-colorpicker-id="2">
                                                <input type="text" id="colorselect" class="form-control" data-original-title="" title="">

                                                <div class="input-group-append">
                                                    <span class="input-group-text"><i class="fas fa-square" style="color: rgb(255, 0, 0);"></i></span>
                                                </div>
                                            </div>*@
                                        @*<label class="form-control-label">Color Selector</label>
                                            <input type="text" id="colorselect" class="form-control" />*@
                                    </div>

                                    <label style="padding-top: 10px!important" class="form-control-label">Color Name<span class="mandatoryAsterisk">*</span></label>
                                    <input type="text" id="colorname" class="form-control" />
                                </div>

                                <div class="row">
                                    <div class="col-2" style="display:none">
                                        <label class="form-control-label">Font Color</label>
                                        <input type="text" id="inputfontcode" class="form-control" />
                                    </div>

                                    <div class="col-4" style="display:none">
                                        <label class="form-control-label">RGB</label>
                                        <input id="inputrgbcode" disabled class="form-control" />
                                    </div>
                                    <div style="display:none">
                                        <label class="form-control-label">Hex Code</label>
                                        <input type="text" disabled id="inputhexcode" class="form-control" />
                                    </div>

                                </div>
                                <div style="margin-top:10px;margin-bottom:10px!important;">
                                    <div class="modal-footer col" style="padding-right:7.5px!important; align-items:flex-end!important">
                                        <button type="submit" id="btnCancel" class="btn btn-tool">Cancel</button>
                                        <button type="submit" id="btnSubmit" class="btn btn-info">Save</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <!-- /.card-footer-->
                </div>
            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>